/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 css-3d.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/css-3d.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[20.789, 136.746, 10.172]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.005"]}
          position={[-142.941, -32.748, -5922.869]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <group position={[326.27, 35.487, 1926.616]}>
          <mesh
            geometry={nodes.Mesh001.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Mesh001_1.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.ramka2.geometry}
          material={materials["Material.001"]}
          position={[-182.684, 35.487, 1926.616]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/css-3d.glb");
